name: Update Impact Stars
on:
  schedule:
  - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install PyGithub
      - name: Run calculation
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python .github/scripts/calculate_stars.py
      - name: Commit and push if changed
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add stars_data.json
          git commit -m "Update star count" || exit 0
          git push
